name: CI

on:
  push:
    branches: [main, update/workflows]
    paths: [src/*, ts/*, .github/workflows/ci.yaml]
  pull_request:

jobs:
  ci:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    
    - run: npm ci --include=dev
    - run: npm run build    
    - run: npm run test
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}