name: todocheck-bot

on:
  issues:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        node_version:
          - 12
        architecture:
          - x64

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}

      - name: Install dependencies
        run: npm ci --include=dev

      - name: Build
        run: npm run build

      - name: Tests
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: npm run test