name: todocheck-bot

on:
  issues:
    types:
      - closed

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        node_version:
          - 14
        architecture:
          - x64

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}

      - name: "Prepare"
        run: |-
          sudo apt-get update
          sudo apt-get install -y curl

      - name: Install dependencies
        run: npm ci --include=dev

      - name: Fetch todocheck 
        run: |-
          curl -sSLf --tlsv1.2 \
            https://github.com/preslavmihaylov/todocheck/releases/download/0.4.1/todocheck-0.4.1-linux-x86_64 \
            -o todocheck-linux
          chmod +x todocheck-linux

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Tests
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: npm run test