name: Publish

on:
  release:
    types: [published, edited]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm ci
      - run: npm install @vercel/ncc convert-action --no-save
      - run: npm run build && npm run deploy-build

      - name: build and tag
        uses: JasonEtco/build-and-tag-action@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}