name: publish

on:
  workflow_run:
    workflows: [ci]
    types: [completed]
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: build and tag
        uses: JasonEtco/build-and-tag-action@v2
        with:
          ref: ${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}