name: Publish

on:
  release:
    types: [published, edited]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - run: npm ci
      - run: npm install @vercel/ncc convert-action
      - run: npm run deploy-build  

      - name: build and tag
        uses: JasonEtco/build-and-tag-action@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}