name: todocheck-bot

on:
  issues:
    types: [closed]

jobs:
  todocheck-bot:
    runs-on: ubuntu-latest

    steps:      
      - name: Fetch codebase
        uses: actions/checkout@v2

      - name: Fetch todocheck binary
        run: |
          curl -sSlL https://github.com/bengsparks/todocheck-bot/releases/download/v0.0.2/todocheck -o todocheck
          chmod +x todocheck

      - name: Setup .todocheck.yaml and auth
        run: |
          echo "origin: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY" >> .todocheck.yaml
          echo "issue_tracker: GITHUB" >> .todocheck.yaml
          echo "auth:" >> .todocheck.yaml
          echo "    type: apitoken" >> .todocheck.yaml

      - name: Status
        run: |
          ls -a1
          cat .todocheck.yaml

      - name: Execute todocheck-bot
        uses: bengsparks/todocheck-bot@v0.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-numbers: ${{ github.event.issue.number }}
        env:
          TODOCHECK_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}